-- ============================================================================
-- Secure Networking Tracker — contacts schema
-- Apply with:  psql "$DATABASE_URL" -f db/schema.sql
-- (or paste into the Neon Console SQL Editor)
--
-- Ownership is enforced by Postgres, not by application code. The Data API
-- verifies the caller's JWT and exposes its `sub` claim to SQL as
-- auth.user_id(); every policy below is written against that function, so a
-- row can only ever be read or written by the user who owns it.
-- ============================================================================

create table if not exists contacts (
  id          bigint generated by default as identity primary key,

  -- Stamped by the database from the verified JWT. The application never
  -- sends this column on insert, so a client cannot claim another user's id.
  user_id     text        not null default (auth.user_id()),

  name        text        not null,
  company     text,
  role        text,
  where_met   text,
  notes       text,
  priority    text        not null default 'medium',

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  -- Sorting by `priority` as text gives high -> low -> medium, which is wrong.
  -- PostgREST cannot express a CASE in an ORDER BY, so the ordering is
  -- materialised here as a sortable integer instead.
  priority_rank smallint generated always as (
    case priority when 'high' then 1 when 'medium' then 2 else 3 end
  ) stored,

  -- Layer 3 validation: these hold even for a request that bypasses the
  -- application's API routes and writes straight to the Data API.
  constraint contacts_name_not_blank check (length(trim(name)) > 0),
  constraint contacts_priority_valid check (priority in ('high', 'medium', 'low'))
);

create index if not exists contacts_user_id_idx  on contacts (user_id);
create index if not exists contacts_priority_idx on contacts (user_id, priority_rank);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
-- Enabling RLS blocks ALL access until a policy grants it. Every policy is
-- scoped to the `authenticated` role; the `anonymous` role is granted nothing,
-- so a signed-out caller can read nothing at all.
alter table contacts enable row level security;

-- Re-runnable: drop before create so this file can be applied more than once.
drop policy if exists contacts_select_own on contacts;
drop policy if exists contacts_insert_own on contacts;
drop policy if exists contacts_update_own on contacts;
drop policy if exists contacts_delete_own on contacts;

-- SELECT: you only ever see your own rows.
create policy contacts_select_own on contacts
  for select to authenticated
  using (auth.user_id() = user_id);

-- INSERT: WITH CHECK runs against the row *after* defaults are applied, so an
-- explicit user_id belonging to someone else is rejected.
create policy contacts_insert_own on contacts
  for insert to authenticated
  with check (auth.user_id() = user_id);

-- UPDATE: USING decides which rows you may edit at all; WITH CHECK decides
-- what they may look like afterwards. Both are required — without WITH CHECK a
-- user could edit their own row and re-assign it to another user_id.
create policy contacts_update_own on contacts
  for update to authenticated
  using (auth.user_id() = user_id)
  with check (auth.user_id() = user_id);

-- DELETE: you may only delete your own rows.
create policy contacts_delete_own on contacts
  for delete to authenticated
  using (auth.user_id() = user_id);

-- ---------------------------------------------------------------------------
-- Table privileges
-- ---------------------------------------------------------------------------
-- RLS filters rows, but the role still needs table privileges to get that far.
-- RLS without GRANT returns a confusing permission error; GRANT without RLS
-- silently exposes every row. Both are required.
grant usage on schema public to authenticated;
grant select, insert, update, delete on table contacts to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Deliberately NOT granted to `anonymous`.
